### ISSUE TITLE
`asdf latest minikube` doesn't list a version

### ISSUE THREAD

**Issue by ksmithut** [alvarobp/asdf-minikube#14]
When you run `asdf latest minikube`, it doesn't print out anything.

```
$ asdf version
v0.7.6
```

```sh
$ asdf plugin list --urls --refs | grep minikube
minikube   https://github.com/alvarobp/asdf-minikube.git        master  5c87ed9
```

**Comment by ksmithut** [comment]
Not sure if it has anything to do with it, but when I run `asdf list all minikube`, it prints out the following:

```
"v0.30.0",.z
"v0.31.0",.z
"v0.32.0",.z
"v0.33.0",.z
"v0.33.1",.z
"v0.34.0",.z
"v0.34.1",.z
"v0.35.0",.z
"v1.0.0",.z
"v1.0.1",.z
"v1.1.0",.z
"v1.1.1",.z
"v1.2.0",.z
"v1.3.0",.z
"v1.3.1",.z
"v1.4.0.beta.0",.z
"v1.4.0.beta.1",.z
"v1.4.0.beta.2",.z
"v1.4.0",.z
"v1.5.0.beta.0",.z
"v1.5.0",.z
"v1.5.1",.z
"v1.5.2",.z
"v1.6.0.beta.0",.z
"v1.6.0.beta.1",.z
"v1.6.0",.z
"v1.6.1",.z
"v1.6.2",.z
"v1.7.0.beta.0",.z
"v1.7.0.beta.1",.z
```

Not sure what the `.z` is about, but perhaps something isn't parsing correctly?

**Comment by ksmithut** [comment]
I will say that this is only on a Mac. My linux machine seems to be working just fine. Perhaps something to do with [this line?](https://github.com/alvarobp/asdf-minikube/blob/master/bin/list-all#L17)

**Comment by alvarobp** [comment]
I'm sorry @ksmithut for the late reply, I just realised this issue. There's something fishy with my Github notifications. 

I'll take a look as soon as I can.

Thanks for reporting this issue.

**Comment by ksmithut** [comment]
No worries, and no rush :+1:

**Comment by alvarobp** [comment]
I took a look at the issue but the CI builds kept failing on OSX. 

Since there were other issues open and I couldn't find a way to get CI builds to pass I tried rewriting the plugin according to a more recent one: https://github.com/alvarobp/asdf-minikube/pull/15 

master version of the plugin should now work fine, or at least allow to accept PRs expecting CI builds to pass.

Thank you for your contribution!
